### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by davidlehn**
Some additional modernization of the dependencies.  This was from a work-in-progress a while ago.  At the time I was trying to update the various vue related packages to be able to run tests.  This hasn't been tested yet with those packages.

### CODE REVIEW

**Comment by mattcollier** [comment]
The *first* error I get with this patch is:
```
matt@matt-X570-AORUS-ELITE:~/bedrock-dev/bedrock-web-zcap-storage/test$ npm test

> bedrock-web-zcap-storage-test@0.0.1-0 test /home/matt/bedrock-dev/bedrock-web-zcap-storage/test
> node --preserve-symlinks test.js test

(node:28051) DeprecationWarning: runOnceAsync() is deprecated. Use runOnce() instead.
Running Test Frameworks...

Running Mocha tests...

  0 passing (0ms)

Tests exited with error [TypeError: Cannot read property 'push' of undefined
  at /home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-karma/lib/test.js:57:23
  at Array.forEach (<anonymous>:null:null)
  at generateKarmaConfig (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-karma/lib/test.js:54:44)
  at /home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-karma/lib/test.js:29:25
  at new Promise (<anonymous>:null:null)
  at run (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-karma/lib/test.js:18:10)
  at /home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-karma/lib/test.js:13:12
  at EventEmitter.emit (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/async-node-events/lib/main.js:146:26)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at /home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-test/lib/test.js:54:9
  at Object.api.runOnce (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock/lib/bedrock.js:201:5)
  at /home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock-test/lib/test.js:50:5
  at EventEmitter.emit (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/async-node-events/lib/main.js:146:20)
  at _runWorker (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock/lib/bedrock.js:498:3)
  at Object.api.start (/home/matt/bedrock-dev/bedrock-web-zcap-storage/test/node_modules/bedrock/lib/bedrock.js:139:5)
]
2020-02-05T14:33:27.678Z - critical: [bedrock/master] worker "28051" exited with code "0"

```

if I add a `files` property to the config, other errors appear.  Please test with https://github.com/digitalbazaar/bedrock-web-zcap-storage/tree/initial

**Comment by mattcollier** [comment]
@davidlehn sorry, I squashed commits on this branch.  Maybe you can force push your local copy.

**Comment by davidlehn** [comment]
I got a bit confused so just rebased my local changes on new master and pushed to `update-deps-2`.  Repush here as needed.  Also test.

**Comment by dlongley** [comment]
@davidlehn -- please close this if stale.

**Comment by davidlehn** [comment]
I can only assume this is now quite out of date.  Closing.

**Pull request closed without merging**
